# Generated by Django 2.2.3 on 2021-11-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0003_auto_20211113_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fechaPubli',
            field=models.DateField(verbose_name='fecha inicio'),
        ),
    ]
