# Generated by Django 3.2.9 on 2021-12-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0003_libro_numvaloraciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='texto',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
