# Generated by Django 2.2.3 on 2021-11-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0006_remove_libro_fechapubli'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fechaPubli',
            field=models.DateField(default=False),
            preserve_default=False,
        ),
    ]
