# Generated by Django 2.2.3 on 2021-11-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0007_libro_fechapubli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='fechaPubli',
            new_name='fecha_publi',
        ),
    ]
