# Generated by Django 2.2.3 on 2021-11-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0010_libro_fecha_publi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publi',
            field=models.DateField(null=True),
        ),
    ]
