# Generated by Django 2.2.3 on 2021-11-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0012_auto_20211113_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
