# Generated by Django 2.2.3 on 2021-11-13 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0013_auto_20211113_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publi',
            field=models.DateField(default=datetime.date),
            preserve_default=False,
        ),
    ]
