# Generated by Django 3.2.9 on 2021-11-16 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0016_libro_fechapubli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fechaPubli',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 13, 26, 42, 516113, tzinfo=utc)),
        ),
    ]
