# Generated by Django 3.2.9 on 2022-01-11 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0006_alter_usuario_notificar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='puntuacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
